Rental/Models/DataContext.cs


using Microsoft.EntityFrameworkCore;

namespace Rental.Models{

    /*
        this class will handle the connection to DB
        and helps to retrueve/store/update data

        if something changes on the models/tables, exec:
        -dotnet ef migrations add <someName>
        -dotner ef database update
    */

    public class DataContext: DbContext {

        public DataContext( DbContextOptions<DataContext> options ) : base(options) {

        }

        public DbSet<Weapon> Weapons {get; set;}

    }
}

Rental/Models/ErrorViewModel.cs
using System;

namespace Rental.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rental/Models/PlayerCharacter.cs

namespace Rental.Models{
    public class PlayerCharacter{
        public string Name { get; set }

        public int Health { get; set }

        public int HitPercent { get; set }

        public int Damage { get; set }
        
        public int Reflex { get; set }

        public int Armor { get; set }

        public int Strength { get; set }

        public int Dexterity { get; set }

        public int Intelligence { get; set }

    }
}

Rental/Models/Weapon.cs

namespace Rental.Models{
    public class Weapon{
        public int Id { get; set; }

        public string Name { get; set; }

        public string Price { get; set; }

        public string Type { get; set; }

        public string Damage { get; set; }

        public string Requirements { get; set; }

        public string Description { get; set; }

        public string ImageUrl { get; set; }
    }
}

Rental/Controllers/CatalogController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Rental.Models;
using System.Collections.Generic;
using System.Linq;

namespace Rental.Controllers
{
    public class CatalogController : Controller
    {
        private DataContext dbContext;
        public CatalogController(DataContext context){
            this.dbContext = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]

        public IActionResult SaveWeapon([FromBody] Weapon theWeapon){
            Console.WriteLine("User is saving a weapon");

            dbContext.Weapons.Add(theWeapon);
            dbContext.SaveChanges();
            
            return Json(theWeapon);
        }

        [HttpGet]
        public IActionResult GetCatalog(){
            /* Weapon w1 = new Weapon();
            w1.Name = "";
            w1.Price = ;
            w1.Type = "";
            w1.Damage = ;
            w1.Requirement = "";
            w1.ImageUrl = "";
            w1.Description = ""; */

            var list = dbContext.Weapons.ToList();
            return Json(list);
        }
    }
}

Rental/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rental.Models;

namespace Rental.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test(){
            return View();
        }

        public IActionResult Home(){
            return View();
        }

        public IActionResult About(){
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rental/Views/Catalog/Index.cshtml

@{
    ViewData["Title"] = "Index";
}
<body>
    <header>
        <h1>Hunter's Workshop</h1>
    </header>

    <main>
        <div class="container">
            <div id="catalog" class="catalog">
                <!--render items here-->
            </div>
        </div>
    </main>
</body>

@section Styles{
    <link href="/css/catalog.css" rel="stylesheet">
}
@section Scripts{
    <script src="/js/Catalog/catalog.js"></script>
}

Rental/Views/Catalog/Register.cshtml
@{
ViewData["Title"] = "Register Item";
}

<h1>Sell your Weapons to the Workshop</h1>



<div class="row">

    <div class="form-group col-md-4" id="label">
        <br>
        <label for="wname"> Name: </label><br>
        <label for="type">Type: </label><br>
        <label for="wdamage">Damage: </label><br>
        <label for="wrequirements">Requirements: </label><br>
        <label for="wprice">Price: </label><br>
        <label for="wdescription">Description: </label><br>
        <label for="wimageurl">Image URL: </label>
    </div>

    <div class="form-group col-md-8" id="input"><br>
        <input type="text" id="wname" name="wname"><br>
        <div class="radio-inline" id="wtype">
                <label><input type="radio" name="optradio" value="1">Trick Weapon</label>
                <label><input type="radio" name="optradio" value="2">Fire Arm</label>
                <label><input type="radio" name="optradio" value="3">Hunter Tool</label>
        </div>
        <input type="Text" id="wdamage" name="wdamage">
        <select class="form-control" id="wdamagetype">
            <option value="1">Physical</option>
            <option value="2">Blood</option>
            <option value="3">Arcane</option>
            <option value="4">Fire</option>
            <option value="5">Bolt</option>
        </select><br>
        <input type="text" id="wrequirements" name="wrequirements"><br>
        <input type="text" id="wprice" name="wprice"><br>
        <input type="text" id="wdescription" name="wdescription"><br>
        <input type="text" id="wimageurl" name="wimageurl">
    </div>

    <div class="button">
        <button id="btnSave" class="btn btn-primary">Register Weapon</button>
    </div>
</div>

@section Styles{
    <link href="/css/register.css" rel="stylesheet">
}
@section Scripts{
    <script src="/js/Catalog/register.js"></script>
}

Rental/Views/Home/About.cshtml

@{
    ViewData["Title"] = "About";
}

<h1>C G Seabaugh</h1>

Rental/Views/Home/Home.cshtml

@{
    ViewData["Title"] = "Home";
}

<h1>Home</h1>

Rental/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rental/Views/Home/Test.cshtml


<h1>Hello World</h1>

Rental/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rental</title>
    <link rel="icon" href="/img/Military-Sword-icon.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rental</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Catalog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Register">Register Weapon</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Rental - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>